# Generated by Django 5.2.8 on 2025-11-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(max_length=100, verbose_name="نام نویسنده"),
                ),
                (
                    "author_job",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="سمت"
                    ),
                ),
                ("quote", models.TextField(verbose_name="متن نظر")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "★"),
                            (2, "★★"),
                            (3, "★★★"),
                            (4, "★★★★"),
                            (5, "★★★★★"),
                        ],
                        default=5,
                        verbose_name="امتیاز",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="testimonials/avatars/",
                        verbose_name="آواتار",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "نظر مشتری",
                "verbose_name_plural": "نظرات مشتریان",
                "ordering": ["-created_at"],
            },
        ),
    ]
