# Generated by Django 5.2.8 on 2025-11-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_contactmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("primary", models.CharField(default="#0a0a0a", max_length=7)),
                ("accent", models.CharField(default="#6d4677", max_length=7)),
                ("accent_hover", models.CharField(default="#d763a6", max_length=7)),
                ("text_light", models.CharField(default="#ffffff", max_length=7)),
                ("text_muted", models.CharField(default="#999999", max_length=7)),
                ("bg_dark", models.CharField(default="#000000", max_length=7)),
                ("bg_dark_second", models.CharField(default="#222222", max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
