# Generated by Django 5.2.8 on 2025-11-30 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_theme"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان معرفی")),
                ("description", models.TextField(verbose_name="توضیحات معرفی")),
                (
                    "homepage_description",
                    models.TextField(verbose_name="الرئیسیه Description"),
                ),
                ("vision", models.TextField(verbose_name="رؤيتنا")),
                ("location", models.CharField(max_length=255, verbose_name="موقعنا")),
            ],
            options={
                "verbose_name": "تنظیمات سایت",
                "verbose_name_plural": "تنظیمات سایت",
            },
        ),
        migrations.AlterField(
            model_name="theme",
            name="accent",
            field=models.CharField(
                default="#6d4677", max_length=7, verbose_name="متن 2"
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="accent_hover",
            field=models.CharField(
                default="#d763a6", max_length=7, verbose_name="هاور متن"
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="bg_dark",
            field=models.CharField(
                default="#000000", max_length=7, verbose_name="رنگ زمینه"
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="bg_dark_second",
            field=models.CharField(
                default="#222222", max_length=7, verbose_name="رنگ زمینه 2"
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="primary",
            field=models.CharField(
                default="#0a0a0a", max_length=7, verbose_name="اصلی"
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="text_light",
            field=models.CharField(default="#ffffff", max_length=7, verbose_name="متن"),
        ),
        migrations.AlterField(
            model_name="theme",
            name="text_muted",
            field=models.CharField(
                default="#999999", max_length=7, verbose_name="رنگ متن توضیح "
            ),
        ),
        migrations.CreateModel(
            name="PhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=50, verbose_name="شماره تلفن")),
                (
                    "setting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phones",
                        to="product.sitesetting",
                        verbose_name="تنظیمات مربوطه",
                    ),
                ),
            ],
            options={
                "verbose_name": "شماره تلفن",
                "verbose_name_plural": "شماره\u200cهای تلفن",
            },
        ),
    ]
