# Generated by Django 5.2.8 on 2025-11-30 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_sitesetting_alter_theme_accent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesetting",
            name="description",
        ),
        migrations.RemoveField(
            model_name="sitesetting",
            name="title",
        ),
        migrations.AddField(
            model_name="phonenumber",
            name="name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="نام"
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="about_description",
            field=models.TextField(blank=True, null=True, verbose_name="توضیحات معرفی"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="about_title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="عنوان معرفی"
            ),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="شماره تلفن"
            ),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="setting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phones",
                to="product.sitesetting",
                verbose_name="تنظیمات مربوطه",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="homepage_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="الرئیسیه Description"
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="location",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="موقعنا"
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="vision",
            field=models.TextField(blank=True, null=True, verbose_name="رؤيتنا"),
        ),
    ]
