# Generated by Django 5.2.8 on 2025-11-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_remove_sitesetting_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesetting",
            name="location",
            field=models.TextField(
                blank=True, null=True, verbose_name="موقع علی الگوگل"
            ),
        ),
    ]
