# Generated by Django 5.2.8 on 2025-12-06 16:54

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_alter_sitesetting_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="content",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="محتوا"
            ),
        ),
        migrations.CreateModel(
            name="ProductFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, verbose_name="ویژگی")),
                ("value", models.CharField(max_length=200, verbose_name="مقدار")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="product.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/product_gallery/")),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="توضیح تصویر",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="product.product",
                    ),
                ),
            ],
        ),
    ]
